###BROADCASTING

In [ ]:
For doing any math operations in numpy for a given matrix , there are two conditions
1. they are equal, or
2. one of them is 1

In [3]:
import numpy as np
import random

In [10]:
a= np.ones((3,2))
b = np.ones((2,3)) # condition 1 Shape should be same
a+b.reshape(3,2)

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [19]:
a = a= np.ones((3,2))
b = np.ones((3,1)) # No. of Rows should be same and  No. of columns should be one.
a+b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [17]:
a = a= np.ones((3,2)) # No. of columns sholud be same and no. of rows should be one
b = np.ones((1, 2))
a+b

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [40]:
a = np.full((3,4,2),4).reshape(2,4,3)
b = np.full((2,4,1),4)
a+b

array([[[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8],
        [8, 8, 8],
        [8, 8, 8]]])

In [69]:
a = np.array([[1,2],[5,2],[4,2]])

b = np.array([[3,1],[4,1]])
res = a.reshape(1,2,3) - b.reshape(2,2,1)
print(res)
# res.shape
m = b.reshape(2,1,2)
# print(m)

# print(b)
a.shape
b.shape


[[[-2 -1  2]
  [ 1  3  1]]

 [[-3 -2  1]
  [ 1  3  1]]]


(2, 2)

In [81]:
a = np.array([[1,2],[5,2],[4,2],[4,6]])

b = np.array([[3,1],[4,1],[3,2]])
m = a.reshape(4,2) - b.reshape(3,1,2)
print(m)



[[[-2  1]
  [ 2  1]
  [ 1  1]
  [ 1  5]]

 [[-3  1]
  [ 1  1]
  [ 0  1]
  [ 0  5]]

 [[-2  0]
  [ 2  0]
  [ 1  0]
  [ 1  4]]]


In [ ]:
Thumb rule : In order to arthematic operations of any matrix there should be:
        1. value and position of one matix must be equal to another
        2. there should be value 1 in both of the cases or sometimes in any one of the cases

###Statistics Using Numpy

In [111]:
# sort and argsort
a = np.array([8,4,3,56,2,54,2,1])

np.sort(a) # return values in ascending order
np.argsort(a) # Returns index of the value which are in ascending order


<built-in method sort of numpy.ndarray object at 0x000000EBF16DE8A0>


In [113]:
# Standard Deviation  std =  sqrt(sum(x-x.mean)**2//n)
a = np.array([8,4,3,56,2,54,2,1])
a.std()

22.465250944514285

In [114]:
# Variance var = std**2
a = np.array([8,4,3,56,2,54,2,1])
a.var()

504.6875

In [115]:
#mean sum(a)/n
a = np.array([8,4,3,56,2,54,2,1])
a.mean()

16.25

In [117]:
#median The median is the ((n + 1)/2)
a = np.array([8,4,3,56,2,54,2,1])
np.median(a)

3.5