In [2]:
import numpy as np
import random

In [3]:
data = np.random.randint(1,100,(5,5))
print(data)
# max(data)


[[17 32 97 90 91]
 [76 31 71 42 68]
 [90 54 31 93 37]
 [36 11 20  1 46]
 [28 27 81 11 77]]


In [4]:
data = np.array([1,1,1])
data.any()


True

In [5]:
data.all()

True

In [6]:
np.choose([1,2,0,1],choices = ["cat","rat","bat","chat"]) #indexing 

array(['rat', 'bat', 'cat', 'rat'], dtype='<U4')

In [15]:
d = np.random.randint(-10,10,20)
d[(d>0)]

array([9, 7, 3, 5, 9, 5, 9, 7, 2, 8, 6])

In [18]:
d[np.where(d>0)] # finding the values which are non-negative

array([9, 7, 3, 5, 9, 5, 9, 7, 2, 8, 6])

In [21]:
d = np.random.randint(1,10,(4,4))
print(d)

[[5 6 8 2]
 [2 1 6 6]
 [7 7 7 8]
 [4 4 5 6]]


In [22]:
np.where(d>5)

(array([0, 0, 1, 1, 2, 2, 2, 2, 3], dtype=int64),
 array([1, 2, 2, 3, 0, 1, 2, 3, 3], dtype=int64))

In [24]:
d = np.random.randint(1,1000,100)
d

array([857, 704, 982, 633, 620,  44, 778, 133, 146,   5, 225,  29, 196,
       942, 754, 683, 714, 146, 951, 721, 429, 824, 489, 776, 698, 220,
        44, 932, 873, 591,  81,  62, 688, 152, 426, 109, 203, 507,  29,
       884, 995, 992, 993, 890, 407, 225, 559, 258, 650, 421, 788, 845,
       960, 268, 765, 337, 484, 213, 541, 681, 224, 213, 749, 927, 494,
       347, 180, 875, 763, 189, 216, 638, 916, 966, 848, 660, 601,  89,
       228, 688, 245, 441, 306, 286, 353, 532, 533, 722, 345, 321, 772,
       180, 571, 100, 765,  38, 274, 590, 184, 866])

In [26]:
d[np.where(d >(np.log2(d) * 10))] # to to find the log of value we do (np.log2(d))

array([857, 704, 982, 633, 620, 778, 133, 146, 225, 196, 942, 754, 683,
       714, 146, 951, 721, 429, 824, 489, 776, 698, 220, 932, 873, 591,
        81,  62, 688, 152, 426, 109, 203, 507, 884, 995, 992, 993, 890,
       407, 225, 559, 258, 650, 421, 788, 845, 960, 268, 765, 337, 484,
       213, 541, 681, 224, 213, 749, 927, 494, 347, 180, 875, 763, 189,
       216, 638, 916, 966, 848, 660, 601,  89, 228, 688, 245, 441, 306,
       286, 353, 532, 533, 722, 345, 321, 772, 180, 571, 100, 765, 274,
       590, 184, 866])